import { Inter } from 'next/font/google';
import './globals.css';
import Navbar from '../Components/Navbar';
import { QueryContextWrapper } from '../context/queryContext';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Dil Foods',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar />
        <QueryContextWrapper>
          <div className="mt-14">{children}</div>
        </QueryContextWrapper>
      </body>
    </html>
  );
}
